// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrilaqozrogkktpmnutl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaWxhcW96cm9na2t0cG1udXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTUwNDMsImV4cCI6MjA3MzQ5MTA0M30.jpdMXi4w6EJvpGCrQglOs_D7L1r0fDY8k4-MZYdDC0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});